### ISSUE TITLE
Lunar Console Pro version crashes at the application start at unity 2023.1.11f1

### ISSUE THREAD

**Issue by blackfxx** [SpaceMadness/lunar-unity-console#219]
After chaging unity version from 2022.2.1f1 to  2023.1.11f1, the game start crashing after Unity logo screen. If remove console from build - everything  is good.
The console works without crash and any issues on the same project with another unity version(2022.2.1f1)

2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime FATAL EXCEPTION: main
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime java.lang.VerifyError: Verifier rejected class spacemadness.com.lunarconsole.console.ManagedPlatform: android.view.View spacemadness.com.lunarconsole.console.ManagedPlatform.getTouchRecipientView() failed to verify: android.view.View spacemadness.com.lunarconsole.console.ManagedPlatform.getTouchRecipientView(): [0x4] returning 'Reference: com.unity3d.player.UnityPlayer', but expected from declaration 'Reference: android.view.View' (declaration of 'spacemadness.com.lunarconsole.console.ManagedPlatform' appears in /data/app/com.company.strategy.medieval.kindoms.conquest-zC-WhMSBN3XQDNnstzBhqA==/base.apk)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at spacemadness.com.lunarconsole.console.NativeBridge$2.execute(NativeBridge.java:89)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at spacemadness.com.lunarconsole.concurrent.DispatchTask.run(DispatchTask.java:66)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:914)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:100)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:224)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7551)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
2023/09/09 14:52:58.516 17839 17839 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by AleksandrEndovitskii** [comment]
Error AndroidRuntime java.lang.VerifyError: Verifier rejected class spacemadness.com.lunarconsole.console.ManagedPlatform: android.view.View spacemadness.com.lunarconsole.console.ManagedPlatform.getTouchRecipientView() failed to verify: android.view.View spacemadness.com.lunarconsole.console.ManagedPlatform.getTouchRecipientView(): [0x4] returning 'Reference: com.unity3d.player.UnityPlayer', but expected from declaration 'Reference: android.view.View' (declaration of 'spacemadness.com.lunarconsole.console.ManagedPlatform' appears in /data/app/

**Comment by VladTempest** [comment]
Yep, same problem. Is there any solution?

**Comment by serzhikivanov** [comment]
Hello.
Same issue with Unity 2023.2.20f1
When I run the built game on Android phone the game crashes right at startup with the same exception

**Comment by weeeBox** [comment]
Fixed in 1.9.0.
