### ISSUE TITLE
Error AndroidRuntime FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by serzhikivanov** [SpaceMadness/lunar-unity-console#222]
Hello.
I'm trying to use the Lunar Console in a Unity game under Editor 2023.2.20f1
When I run the built game on Android phone the game crashes right at startup with the following exception

Error AndroidRuntime FATAL EXCEPTION: main
Error AndroidRuntime Process: com.gameanalyze.bubblespop, PID: 7394
Error AndroidRuntime java.lang.VerifyError: Verifier rejected class spacemadness.com.lunarconsole.console.ManagedPlatform: android.view.View spacemadness.com.lunarconsole.console.ManagedPlatform.getTouchRecipientView() failed to verify: android.view.View spacemadness.com.lunarconsole.console.ManagedPlatform.getTouchRecipientView(): [0x4] returning 'Reference: com.unity3d.player.UnityPlayer', but expected from declaration 'Reference: android.view.View' (declaration of 'spacemadness.com.lunarconsole.console.ManagedPlatform' appears in /data/app/com.gameanalyze.bubblespop-MrkKX_6DY6LB-AbF605_2g==/base.apk!classes2.dex)
Error AndroidRuntime 	at spacemadness.com.lunarconsole.console.NativeBridge$2.execute(NativeBridge.java:89)
Error AndroidRuntime 	at spacemadness.com.lunarconsole.concurrent.DispatchTask.run(DispatchTask.java:66)
Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:883)
Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:100)
Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:224)
Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7562)
Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

Could you please suggest what can be done?

**Comment by serzhikivanov** [comment]
Closing as duplicate.
